// Code generated by cmd/gen-labels; DO NOT EDIT.
// Source: overlay/labels.json (2026-03-30)

export const LABEL_AGENT_CODE_GEN = "agent:code-gen" as const
export const LABEL_AGENT_DISPATCHER = "agent:dispatcher" as const
export const LABEL_AGENT_DOCS = "agent:docs" as const
export const LABEL_AGENT_FEASIBILITY = "agent:feasibility" as const
export const LABEL_AGENT_HUMAN = "agent:human" as const
export const LABEL_AGENT_IDEATION = "agent:ideation" as const
export const LABEL_AGENT_LEGAL = "agent:legal" as const
export const LABEL_AGENT_ORCHESTRATOR = "agent:orchestrator" as const
export const LABEL_AGENT_PC = "agent:pc" as const
export const LABEL_AGENT_QC = "agent:qc" as const
export const LABEL_AGENT_RESEARCH = "agent:research" as const
export const LABEL_AGENT_TEST = "agent:test" as const

export const LABEL_COMPLEXITY_AMBIGUOUS = "complexity:ambiguous" as const
export const LABEL_COMPLEXITY_CLOUD = "complexity:cloud" as const
export const LABEL_COMPLEXITY_LOCAL = "complexity:local" as const

export const LABEL_HUMAN_CREDENTIALS = "human:credentials" as const
export const LABEL_HUMAN_DECISION = "human:decision" as const
export const LABEL_HUMAN_REVIEW = "human:review" as const
export const LABEL_HUMAN_WORKSTATION = "human:workstation" as const

export const LABEL_PHASE_DELIVERY = "phase:delivery" as const
export const LABEL_PHASE_EXECUTION = "phase:execution" as const
export const LABEL_PHASE_GATE = "phase:gate" as const
export const LABEL_PHASE_INTAKE = "phase:intake" as const
export const LABEL_PHASE_KILLED = "phase:killed" as const
export const LABEL_PHASE_PARKED = "phase:parked" as const
export const LABEL_PHASE_REQUIREMENTS = "phase:requirements" as const
export const LABEL_PHASE_RESEARCH = "phase:research" as const
export const LABEL_PHASE_SCAFFOLD = "phase:scaffold" as const

export const LABEL_PRIORITY_CRITICAL = "priority:critical" as const
export const LABEL_PRIORITY_HIGH = "priority:high" as const
export const LABEL_PRIORITY_LOW = "priority:low" as const
export const LABEL_PRIORITY_NORMAL = "priority:normal" as const

export const LABEL_QC_FAIL = "qc:fail" as const
export const LABEL_QC_PASS = "qc:pass" as const
export const LABEL_QC_REVIEW = "qc:review" as const

export const LABEL_STATUS_BLOCKED = "status:blocked" as const
export const LABEL_STATUS_CLAIMED = "status:claimed" as const
export const LABEL_STATUS_DONE = "status:done" as const
export const LABEL_STATUS_IN_PROGRESS = "status:in-progress" as const
export const LABEL_STATUS_NEEDS_HUMAN = "status:needs-human" as const
export const LABEL_STATUS_NEEDS_QC = "status:needs-qc" as const
export const LABEL_STATUS_QUEUED = "status:queued" as const

export const LABEL_WARNING_QUALITY = "warning:quality" as const

export const AGENT_LABELS = [
  LABEL_AGENT_CODE_GEN,
  LABEL_AGENT_DISPATCHER,
  LABEL_AGENT_DOCS,
  LABEL_AGENT_FEASIBILITY,
  LABEL_AGENT_HUMAN,
  LABEL_AGENT_IDEATION,
  LABEL_AGENT_LEGAL,
  LABEL_AGENT_ORCHESTRATOR,
  LABEL_AGENT_PC,
  LABEL_AGENT_QC,
  LABEL_AGENT_RESEARCH,
  LABEL_AGENT_TEST,
] as const

export const COMPLEXITY_LABELS = [
  LABEL_COMPLEXITY_AMBIGUOUS,
  LABEL_COMPLEXITY_CLOUD,
  LABEL_COMPLEXITY_LOCAL,
] as const

export const HUMAN_LABELS = [
  LABEL_HUMAN_CREDENTIALS,
  LABEL_HUMAN_DECISION,
  LABEL_HUMAN_REVIEW,
  LABEL_HUMAN_WORKSTATION,
] as const

export const PHASE_LABELS = [
  LABEL_PHASE_DELIVERY,
  LABEL_PHASE_EXECUTION,
  LABEL_PHASE_GATE,
  LABEL_PHASE_INTAKE,
  LABEL_PHASE_KILLED,
  LABEL_PHASE_PARKED,
  LABEL_PHASE_REQUIREMENTS,
  LABEL_PHASE_RESEARCH,
  LABEL_PHASE_SCAFFOLD,
] as const

export const PRIORITY_LABELS = [
  LABEL_PRIORITY_CRITICAL,
  LABEL_PRIORITY_HIGH,
  LABEL_PRIORITY_LOW,
  LABEL_PRIORITY_NORMAL,
] as const

export const QC_LABELS = [
  LABEL_QC_FAIL,
  LABEL_QC_PASS,
  LABEL_QC_REVIEW,
] as const

export const STATUS_LABELS = [
  LABEL_STATUS_BLOCKED,
  LABEL_STATUS_CLAIMED,
  LABEL_STATUS_DONE,
  LABEL_STATUS_IN_PROGRESS,
  LABEL_STATUS_NEEDS_HUMAN,
  LABEL_STATUS_NEEDS_QC,
  LABEL_STATUS_QUEUED,
] as const

export const WARNING_LABELS = [
  LABEL_WARNING_QUALITY,
] as const

export const HUMAN_STATUS_LABELS = [
  LABEL_AGENT_HUMAN,
  LABEL_STATUS_NEEDS_HUMAN,
] as const

export const ALL_LABELS = [
  ...AGENT_LABELS,
  ...COMPLEXITY_LABELS,
  ...HUMAN_LABELS,
  ...PHASE_LABELS,
  ...PRIORITY_LABELS,
  ...QC_LABELS,
  ...STATUS_LABELS,
  ...WARNING_LABELS,
] as const

export const PRIORITY_ORDER: Record<string, number> = {
  [LABEL_PRIORITY_CRITICAL]: 0,
  [LABEL_PRIORITY_HIGH]: 1,
  [LABEL_PRIORITY_NORMAL]: 2,
  [LABEL_PRIORITY_LOW]: 3,
} as const
