// Command gen-labels reads overlay/labels.json and generates typed label
// constants for Go, TypeScript, and PowerShell. Run via go generate or
// make gen-labels.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
	"unicode"
)

// label mirrors the shape of each entry in overlay/labels.json.
type label struct {
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
}

func main() {
	root := findRepoRoot()

	data, err := os.ReadFile(filepath.Join(root, "overlay", "labels.json")) //nolint:gosec // G304: path is repo-relative, not user input
	if err != nil {
		fatal("read labels.json: %v", err)
	}

	var labels []label
	if err := json.Unmarshal(data, &labels); err != nil {
		fatal("parse labels.json: %v", err)
	}

	// Group labels by prefix.
	groups := make(map[string][]label)
	for _, l := range labels {
		parts := strings.SplitN(l.Name, ":", 2)
		if len(parts) != 2 {
			continue
		}
		groups[parts[0]] = append(groups[parts[0]], l)
	}

	// Priority labels are defined by the Priority type in issue.go but are
	// not in labels.json. Inject them so consumers get a complete set.
	if _, ok := groups["priority"]; !ok {
		groups["priority"] = []label{
			{Name: "priority:critical", Description: "Critical priority"},
			{Name: "priority:high", Description: "High priority"},
			{Name: "priority:normal", Description: "Normal priority"},
			{Name: "priority:low", Description: "Low priority"},
		}
	}

	generateGo(root, labels, groups)
	generateTypeScript(root, labels, groups)
	generatePowerShell(root, labels, groups)
}

// findRepoRoot walks up from the working directory looking for go.mod.
func findRepoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal("could not find repo root (go.mod)")
		}
		dir = parent
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-labels: "+format+"\n", args...)
	os.Exit(1)
}

// ---------- Go generation ----------

func generateGo(root string, all []label, groups map[string][]label) {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/gen-labels; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: overlay/labels.json (%s)\n", time.Now().UTC().Format("2006-01-02"))
	b.WriteString("package models\n\n")

	// Ordered group names for deterministic output.
	groupOrder := []string{"status", "agent", "priority", "complexity", "phase", "human", "qc", "warning"}

	// Label string constants grouped by prefix.
	for _, prefix := range groupOrder {
		lbls, ok := groups[prefix]
		if !ok {
			continue
		}
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })

		fmt.Fprintf(&b, "// %s labels.\n", titleCase(prefix))
		b.WriteString("const (\n")
		for _, l := range lbls {
			constName := goConstName(prefix, l.Name)
			fmt.Fprintf(&b, "\tLabel%s = %q\n", constName, l.Name)
		}
		b.WriteString(")\n\n")
	}

	// AllLabels returns every label in labels.json.
	b.WriteString("// AllLabels returns every label defined in overlay/labels.json.\n")
	b.WriteString("func AllLabels() []string {\n")
	b.WriteString("\treturn []string{\n")
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		for _, l := range lbls {
			fmt.Fprintf(&b, "\t\tLabel%s,\n", goConstName(prefix, l.Name))
		}
	}
	b.WriteString("\t}\n}\n\n")

	// Per-group slice helpers.
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		funcName := titleCase(prefix) + "Labels"
		fmt.Fprintf(&b, "// %s returns all %s:* labels.\n", funcName, prefix)
		fmt.Fprintf(&b, "func %s() []string {\n", funcName)
		b.WriteString("\treturn []string{\n")
		for _, l := range lbls {
			fmt.Fprintf(&b, "\t\tLabel%s,\n", goConstName(prefix, l.Name))
		}
		b.WriteString("\t}\n}\n\n")
	}

	// IsHumanStatus returns true for labels that indicate human involvement.
	b.WriteString("// IsHumanStatus returns true if the label represents a human-related status.\n")
	b.WriteString("func IsHumanStatus(label string) bool {\n")
	b.WriteString("\tswitch label {\n")
	b.WriteString("\tcase LabelStatusNeedsHuman:\n")
	b.WriteString("\t\treturn true\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n}\n\n")

	// HumanSubtypes returns all human:* subtype labels.
	b.WriteString("// HumanSubtypes returns all human:* subtype labels.\n")
	b.WriteString("func HumanSubtypes() []string {\n")
	b.WriteString("\treturn []string{\n")
	lbls := groups["human"]
	sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
	for _, l := range lbls {
		fmt.Fprintf(&b, "\t\tLabel%s,\n", goConstName("human", l.Name))
	}
	b.WriteString("\t}\n}\n")

	outPath := filepath.Join(root, "pkg", "models", "labels_gen.go")
	//nolint:gosec // G306: generated source files need 644
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fatal("write labels_gen.go: %v", err)
	}
	fmt.Println("wrote", outPath)
}

// goConstName converts "status:needs-human" → "StatusNeedsHuman".
func goConstName(prefix, fullName string) string {
	parts := strings.SplitN(fullName, ":", 2)
	if len(parts) != 2 {
		return titleCase(fullName)
	}
	return titleCase(prefix) + toPascal(parts[1])
}

// toPascal converts "needs-human" → "NeedsHuman".
func toPascal(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '-' || r == '_' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// ---------- TypeScript generation ----------

func generateTypeScript(root string, all []label, groups map[string][]label) {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/gen-labels; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: overlay/labels.json (%s)\n\n", time.Now().UTC().Format("2006-01-02"))

	groupOrder := []string{"status", "agent", "priority", "complexity", "phase", "human", "qc", "warning"}

	// Individual constants.
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		for _, l := range lbls {
			constName := tsConstName(prefix, l.Name)
			fmt.Fprintf(&b, "export const %s = %q as const\n", constName, l.Name)
		}
		b.WriteString("\n")
	}

	// Group arrays.
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		arrayName := strings.ToUpper(prefix) + "_LABELS"
		fmt.Fprintf(&b, "export const %s = [\n", arrayName)
		for _, l := range lbls {
			fmt.Fprintf(&b, "  %s,\n", tsConstName(prefix, l.Name))
		}
		b.WriteString("] as const\n\n")
	}

	// HUMAN_STATUS_LABELS for backward compat with MyQueue.tsx usage.
	b.WriteString("export const HUMAN_STATUS_LABELS = [\n")
	b.WriteString("  LABEL_AGENT_HUMAN,\n")
	b.WriteString("  LABEL_STATUS_NEEDS_HUMAN,\n")
	b.WriteString("] as const\n\n")

	// ALL_LABELS.
	b.WriteString("export const ALL_LABELS = [\n")
	for _, prefix := range groupOrder {
		fmt.Fprintf(&b, "  ...%s_LABELS,\n", strings.ToUpper(prefix))
	}
	b.WriteString("] as const\n\n")

	// PRIORITY_ORDER map for MyQueue.tsx.
	b.WriteString("export const PRIORITY_ORDER: Record<string, number> = {\n")
	b.WriteString("  [LABEL_PRIORITY_CRITICAL]: 0,\n")
	b.WriteString("  [LABEL_PRIORITY_HIGH]: 1,\n")
	b.WriteString("  [LABEL_PRIORITY_NORMAL]: 2,\n")
	b.WriteString("  [LABEL_PRIORITY_LOW]: 3,\n")
	b.WriteString("} as const\n")

	outPath := filepath.Join(root, "web", "src", "lib", "labels.ts")
	//nolint:gosec // G306: generated source files need 644
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fatal("write labels.ts: %v", err)
	}
	fmt.Println("wrote", outPath)
}

// tsConstName converts "status:needs-human" → "LABEL_STATUS_NEEDS_HUMAN".
func tsConstName(prefix, fullName string) string {
	parts := strings.SplitN(fullName, ":", 2)
	if len(parts) != 2 {
		return "LABEL_" + strings.ToUpper(strings.ReplaceAll(fullName, "-", "_"))
	}
	suffix := strings.ToUpper(strings.ReplaceAll(parts[1], "-", "_"))
	return "LABEL_" + strings.ToUpper(prefix) + "_" + suffix
}

// ---------- PowerShell generation ----------

func generatePowerShell(root string, all []label, groups map[string][]label) {
	var b strings.Builder

	b.WriteString("# Code generated by cmd/gen-labels; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "# Source: overlay/labels.json (%s)\n\n", time.Now().UTC().Format("2006-01-02"))
	b.WriteString("Set-StrictMode -Version 3.0\n\n")

	groupOrder := []string{"status", "agent", "priority", "complexity", "phase", "human", "qc", "warning"}

	// Individual variables.
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		for _, l := range lbls {
			varName := psVarName(prefix, l.Name)
			fmt.Fprintf(&b, "$%s = '%s'\n", varName, l.Name)
		}
		b.WriteString("\n")
	}

	// Group arrays.
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		arrayName := titleCase(prefix) + "Labels"
		fmt.Fprintf(&b, "$%s = @(\n", arrayName)
		for _, l := range lbls {
			fmt.Fprintf(&b, "    $%s\n", psVarName(prefix, l.Name))
		}
		b.WriteString(")\n\n")
	}

	// HumanStatusLabels for backward compat.
	b.WriteString("$HumanStatusLabels = @(\n")
	b.WriteString("    $LabelAgentHuman\n")
	b.WriteString("    $LabelStatusNeedsHuman\n")
	b.WriteString(")\n\n")

	// AllLabels.
	b.WriteString("$AllLabels = @(\n")
	for _, prefix := range groupOrder {
		fmt.Fprintf(&b, "    $%sLabels\n", titleCase(prefix))
	}
	b.WriteString(")\n\n")

	// Exports.
	b.WriteString("Export-ModuleMember -Variable @(\n")
	for _, prefix := range groupOrder {
		lbls := groups[prefix]
		sort.Slice(lbls, func(i, j int) bool { return lbls[i].Name < lbls[j].Name })
		for _, l := range lbls {
			fmt.Fprintf(&b, "    '%s'\n", psVarName(prefix, l.Name))
		}
	}
	for _, prefix := range groupOrder {
		fmt.Fprintf(&b, "    '%sLabels'\n", titleCase(prefix))
	}
	b.WriteString("    'HumanStatusLabels'\n")
	b.WriteString("    'AllLabels'\n")
	b.WriteString(")\n")

	outPath := filepath.Join(root, "scripts", "pc-agent", "labels.psm1")
	//nolint:gosec // G306: generated source files need 644
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fatal("write labels.psm1: %v", err)
	}
	fmt.Println("wrote", outPath)
}

// psVarName converts "status:needs-human" → "LabelStatusNeedsHuman".
func psVarName(prefix, fullName string) string {
	return "Label" + goConstName(prefix, fullName)
}
