// Code generated by cmd/gen-labels; DO NOT EDIT.
// Source: overlay/labels.json (2026-03-30)
package models

// Agent labels.
const (
	LabelAgentCodeGen = "agent:code-gen"
	LabelAgentDispatcher = "agent:dispatcher"
	LabelAgentDocs = "agent:docs"
	LabelAgentFeasibility = "agent:feasibility"
	LabelAgentHuman = "agent:human"
	LabelAgentIdeation = "agent:ideation"
	LabelAgentLegal = "agent:legal"
	LabelAgentOrchestrator = "agent:orchestrator"
	LabelAgentPc = "agent:pc"
	LabelAgentQc = "agent:qc"
	LabelAgentResearch = "agent:research"
	LabelAgentTest = "agent:test"
)

// Complexity labels.
const (
	LabelComplexityAmbiguous = "complexity:ambiguous"
	LabelComplexityCloud = "complexity:cloud"
	LabelComplexityLocal = "complexity:local"
)

// Doc labels.
const (
	LabelDocDecisionReview = "doc:decision-review"
	LabelDocInconsistent = "doc:inconsistent"
	LabelDocStale = "doc:stale"
	LabelDocStructure = "doc:structure"
)

// Human labels.
const (
	LabelHumanCredentials = "human:credentials"
	LabelHumanDecision = "human:decision"
	LabelHumanReview = "human:review"
	LabelHumanWorkstation = "human:workstation"
)

// Phase labels.
const (
	LabelPhaseDelivery = "phase:delivery"
	LabelPhaseExecution = "phase:execution"
	LabelPhaseGate = "phase:gate"
	LabelPhaseIntake = "phase:intake"
	LabelPhaseKilled = "phase:killed"
	LabelPhaseParked = "phase:parked"
	LabelPhaseRequirements = "phase:requirements"
	LabelPhaseResearch = "phase:research"
	LabelPhaseScaffold = "phase:scaffold"
)

// Priority labels.
const (
	LabelPriorityCritical = "priority:critical"
	LabelPriorityHigh = "priority:high"
	LabelPriorityLow = "priority:low"
	LabelPriorityNormal = "priority:normal"
)

// Qc labels.
const (
	LabelQcFail = "qc:fail"
	LabelQcPass = "qc:pass"
	LabelQcReview = "qc:review"
)

// Status labels.
const (
	LabelStatusBlocked = "status:blocked"
	LabelStatusClaimed = "status:claimed"
	LabelStatusDone = "status:done"
	LabelStatusInProgress = "status:in-progress"
	LabelStatusNeedsHuman = "status:needs-human"
	LabelStatusNeedsQc = "status:needs-qc"
	LabelStatusQueued = "status:queued"
)

// Warning labels.
const (
	LabelWarningQuality = "warning:quality"
)

// AllLabels returns every label defined in overlay/labels.json.
func AllLabels() []string {
	return []string{
		LabelAgentCodeGen,
		LabelAgentDispatcher,
		LabelAgentDocs,
		LabelAgentFeasibility,
		LabelAgentHuman,
		LabelAgentIdeation,
		LabelAgentLegal,
		LabelAgentOrchestrator,
		LabelAgentPc,
		LabelAgentQc,
		LabelAgentResearch,
		LabelAgentTest,
		LabelComplexityAmbiguous,
		LabelComplexityCloud,
		LabelComplexityLocal,
		LabelDocDecisionReview,
		LabelDocInconsistent,
		LabelDocStale,
		LabelDocStructure,
		LabelHumanCredentials,
		LabelHumanDecision,
		LabelHumanReview,
		LabelHumanWorkstation,
		LabelPhaseDelivery,
		LabelPhaseExecution,
		LabelPhaseGate,
		LabelPhaseIntake,
		LabelPhaseKilled,
		LabelPhaseParked,
		LabelPhaseRequirements,
		LabelPhaseResearch,
		LabelPhaseScaffold,
		LabelPriorityCritical,
		LabelPriorityHigh,
		LabelPriorityLow,
		LabelPriorityNormal,
		LabelQcFail,
		LabelQcPass,
		LabelQcReview,
		LabelStatusBlocked,
		LabelStatusClaimed,
		LabelStatusDone,
		LabelStatusInProgress,
		LabelStatusNeedsHuman,
		LabelStatusNeedsQc,
		LabelStatusQueued,
		LabelWarningQuality,
	}
}

// AgentLabels returns all agent:* labels.
func AgentLabels() []string {
	return []string{
		LabelAgentCodeGen,
		LabelAgentDispatcher,
		LabelAgentDocs,
		LabelAgentFeasibility,
		LabelAgentHuman,
		LabelAgentIdeation,
		LabelAgentLegal,
		LabelAgentOrchestrator,
		LabelAgentPc,
		LabelAgentQc,
		LabelAgentResearch,
		LabelAgentTest,
	}
}

// ComplexityLabels returns all complexity:* labels.
func ComplexityLabels() []string {
	return []string{
		LabelComplexityAmbiguous,
		LabelComplexityCloud,
		LabelComplexityLocal,
	}
}

// DocLabels returns all doc:* labels.
func DocLabels() []string {
	return []string{
		LabelDocDecisionReview,
		LabelDocInconsistent,
		LabelDocStale,
		LabelDocStructure,
	}
}

// HumanLabels returns all human:* labels.
func HumanLabels() []string {
	return []string{
		LabelHumanCredentials,
		LabelHumanDecision,
		LabelHumanReview,
		LabelHumanWorkstation,
	}
}

// PhaseLabels returns all phase:* labels.
func PhaseLabels() []string {
	return []string{
		LabelPhaseDelivery,
		LabelPhaseExecution,
		LabelPhaseGate,
		LabelPhaseIntake,
		LabelPhaseKilled,
		LabelPhaseParked,
		LabelPhaseRequirements,
		LabelPhaseResearch,
		LabelPhaseScaffold,
	}
}

// PriorityLabels returns all priority:* labels.
func PriorityLabels() []string {
	return []string{
		LabelPriorityCritical,
		LabelPriorityHigh,
		LabelPriorityLow,
		LabelPriorityNormal,
	}
}

// QcLabels returns all qc:* labels.
func QcLabels() []string {
	return []string{
		LabelQcFail,
		LabelQcPass,
		LabelQcReview,
	}
}

// StatusLabels returns all status:* labels.
func StatusLabels() []string {
	return []string{
		LabelStatusBlocked,
		LabelStatusClaimed,
		LabelStatusDone,
		LabelStatusInProgress,
		LabelStatusNeedsHuman,
		LabelStatusNeedsQc,
		LabelStatusQueued,
	}
}

// WarningLabels returns all warning:* labels.
func WarningLabels() []string {
	return []string{
		LabelWarningQuality,
	}
}

// IsHumanStatus returns true if the label represents a human-related status.
func IsHumanStatus(label string) bool {
	switch label {
	case LabelStatusNeedsHuman:
		return true
	default:
		return false
	}
}

// HumanSubtypes returns all human:* subtype labels.
func HumanSubtypes() []string {
	return []string{
		LabelHumanCredentials,
		LabelHumanDecision,
		LabelHumanReview,
		LabelHumanWorkstation,
	}
}
