// Code generated by cmd/gen-labels; DO NOT EDIT.
// Source: overlay/labels.json (2026-03-25)
package models

// Status labels.
const (
	LabelStatusBlocked = "status:blocked"
	LabelStatusClaimed = "status:claimed"
	LabelStatusDone = "status:done"
	LabelStatusInProgress = "status:in-progress"
	LabelStatusNeedsHuman = "status:needs-human"
	LabelStatusNeedsQc = "status:needs-qc"
	LabelStatusQueued = "status:queued"
)

// Agent labels.
const (
	LabelAgentCodeGen = "agent:code-gen"
	LabelAgentDispatcher = "agent:dispatcher"
	LabelAgentDocs = "agent:docs"
	LabelAgentFeasibility = "agent:feasibility"
	LabelAgentHuman = "agent:human"
	LabelAgentIdeation = "agent:ideation"
	LabelAgentLegal = "agent:legal"
	LabelAgentOrchestrator = "agent:orchestrator"
	LabelAgentPc = "agent:pc"
	LabelAgentQc = "agent:qc"
	LabelAgentResearch = "agent:research"
	LabelAgentTest = "agent:test"
)

// Priority labels.
const (
	LabelPriorityCritical = "priority:critical"
	LabelPriorityHigh = "priority:high"
	LabelPriorityLow = "priority:low"
	LabelPriorityNormal = "priority:normal"
)

// Complexity labels.
const (
	LabelComplexityAmbiguous = "complexity:ambiguous"
	LabelComplexityCloud = "complexity:cloud"
	LabelComplexityLocal = "complexity:local"
)

// Phase labels.
const (
	LabelPhaseDelivery = "phase:delivery"
	LabelPhaseExecution = "phase:execution"
	LabelPhaseGate = "phase:gate"
	LabelPhaseIntake = "phase:intake"
	LabelPhaseKilled = "phase:killed"
	LabelPhaseParked = "phase:parked"
	LabelPhaseRequirements = "phase:requirements"
	LabelPhaseResearch = "phase:research"
	LabelPhaseScaffold = "phase:scaffold"
)

// AllLabels returns every label defined in overlay/labels.json.
func AllLabels() []string {
	return []string{
		LabelStatusBlocked,
		LabelStatusClaimed,
		LabelStatusDone,
		LabelStatusInProgress,
		LabelStatusNeedsHuman,
		LabelStatusNeedsQc,
		LabelStatusQueued,
		LabelAgentCodeGen,
		LabelAgentDispatcher,
		LabelAgentDocs,
		LabelAgentFeasibility,
		LabelAgentHuman,
		LabelAgentIdeation,
		LabelAgentLegal,
		LabelAgentOrchestrator,
		LabelAgentPc,
		LabelAgentQc,
		LabelAgentResearch,
		LabelAgentTest,
		LabelPriorityCritical,
		LabelPriorityHigh,
		LabelPriorityLow,
		LabelPriorityNormal,
		LabelComplexityAmbiguous,
		LabelComplexityCloud,
		LabelComplexityLocal,
		LabelPhaseDelivery,
		LabelPhaseExecution,
		LabelPhaseGate,
		LabelPhaseIntake,
		LabelPhaseKilled,
		LabelPhaseParked,
		LabelPhaseRequirements,
		LabelPhaseResearch,
		LabelPhaseScaffold,
	}
}

// StatusLabels returns all status:* labels.
func StatusLabels() []string {
	return []string{
		LabelStatusBlocked,
		LabelStatusClaimed,
		LabelStatusDone,
		LabelStatusInProgress,
		LabelStatusNeedsHuman,
		LabelStatusNeedsQc,
		LabelStatusQueued,
	}
}

// AgentLabels returns all agent:* labels.
func AgentLabels() []string {
	return []string{
		LabelAgentCodeGen,
		LabelAgentDispatcher,
		LabelAgentDocs,
		LabelAgentFeasibility,
		LabelAgentHuman,
		LabelAgentIdeation,
		LabelAgentLegal,
		LabelAgentOrchestrator,
		LabelAgentPc,
		LabelAgentQc,
		LabelAgentResearch,
		LabelAgentTest,
	}
}

// PriorityLabels returns all priority:* labels.
func PriorityLabels() []string {
	return []string{
		LabelPriorityCritical,
		LabelPriorityHigh,
		LabelPriorityLow,
		LabelPriorityNormal,
	}
}

// ComplexityLabels returns all complexity:* labels.
func ComplexityLabels() []string {
	return []string{
		LabelComplexityAmbiguous,
		LabelComplexityCloud,
		LabelComplexityLocal,
	}
}

// PhaseLabels returns all phase:* labels.
func PhaseLabels() []string {
	return []string{
		LabelPhaseDelivery,
		LabelPhaseExecution,
		LabelPhaseGate,
		LabelPhaseIntake,
		LabelPhaseKilled,
		LabelPhaseParked,
		LabelPhaseRequirements,
		LabelPhaseResearch,
		LabelPhaseScaffold,
	}
}

// IsHumanStatus returns true if the label represents a human-related status.
func IsHumanStatus(label string) bool {
	switch label {
	case LabelStatusNeedsHuman:
		return true
	default:
		return false
	}
}

// HumanSubtypes returns status labels related to human involvement.
// This will expand when needs-human subcategories are added (#217).
func HumanSubtypes() []string {
	return []string{
		LabelStatusNeedsHuman,
	}
}
