# Code generated by cmd/gen-labels; DO NOT EDIT.
# Source: overlay/labels.json (2026-03-29)

Set-StrictMode -Version 3.0

$LabelStatusBlocked = 'status:blocked'
$LabelStatusClaimed = 'status:claimed'
$LabelStatusDone = 'status:done'
$LabelStatusInProgress = 'status:in-progress'
$LabelStatusNeedsHuman = 'status:needs-human'
$LabelStatusNeedsQc = 'status:needs-qc'
$LabelStatusQueued = 'status:queued'

$LabelAgentCodeGen = 'agent:code-gen'
$LabelAgentDispatcher = 'agent:dispatcher'
$LabelAgentDocs = 'agent:docs'
$LabelAgentFeasibility = 'agent:feasibility'
$LabelAgentHuman = 'agent:human'
$LabelAgentIdeation = 'agent:ideation'
$LabelAgentLegal = 'agent:legal'
$LabelAgentOrchestrator = 'agent:orchestrator'
$LabelAgentPc = 'agent:pc'
$LabelAgentQc = 'agent:qc'
$LabelAgentResearch = 'agent:research'
$LabelAgentTest = 'agent:test'

$LabelPriorityCritical = 'priority:critical'
$LabelPriorityHigh = 'priority:high'
$LabelPriorityLow = 'priority:low'
$LabelPriorityNormal = 'priority:normal'

$LabelComplexityAmbiguous = 'complexity:ambiguous'
$LabelComplexityCloud = 'complexity:cloud'
$LabelComplexityLocal = 'complexity:local'

$LabelPhaseDelivery = 'phase:delivery'
$LabelPhaseExecution = 'phase:execution'
$LabelPhaseGate = 'phase:gate'
$LabelPhaseIntake = 'phase:intake'
$LabelPhaseKilled = 'phase:killed'
$LabelPhaseParked = 'phase:parked'
$LabelPhaseRequirements = 'phase:requirements'
$LabelPhaseResearch = 'phase:research'
$LabelPhaseScaffold = 'phase:scaffold'

$LabelHumanCredentials = 'human:credentials'
$LabelHumanDecision = 'human:decision'
$LabelHumanReview = 'human:review'
$LabelHumanWorkstation = 'human:workstation'

$StatusLabels = @(
    $LabelStatusBlocked
    $LabelStatusClaimed
    $LabelStatusDone
    $LabelStatusInProgress
    $LabelStatusNeedsHuman
    $LabelStatusNeedsQc
    $LabelStatusQueued
)

$AgentLabels = @(
    $LabelAgentCodeGen
    $LabelAgentDispatcher
    $LabelAgentDocs
    $LabelAgentFeasibility
    $LabelAgentHuman
    $LabelAgentIdeation
    $LabelAgentLegal
    $LabelAgentOrchestrator
    $LabelAgentPc
    $LabelAgentQc
    $LabelAgentResearch
    $LabelAgentTest
)

$PriorityLabels = @(
    $LabelPriorityCritical
    $LabelPriorityHigh
    $LabelPriorityLow
    $LabelPriorityNormal
)

$ComplexityLabels = @(
    $LabelComplexityAmbiguous
    $LabelComplexityCloud
    $LabelComplexityLocal
)

$PhaseLabels = @(
    $LabelPhaseDelivery
    $LabelPhaseExecution
    $LabelPhaseGate
    $LabelPhaseIntake
    $LabelPhaseKilled
    $LabelPhaseParked
    $LabelPhaseRequirements
    $LabelPhaseResearch
    $LabelPhaseScaffold
)

$HumanLabels = @(
    $LabelHumanCredentials
    $LabelHumanDecision
    $LabelHumanReview
    $LabelHumanWorkstation
)

$HumanStatusLabels = @(
    $LabelAgentHuman
    $LabelStatusNeedsHuman
)

$AllLabels = @(
    $StatusLabels
    $AgentLabels
    $PriorityLabels
    $ComplexityLabels
    $PhaseLabels
    $HumanLabels
)

Export-ModuleMember -Variable @(
    'LabelStatusBlocked'
    'LabelStatusClaimed'
    'LabelStatusDone'
    'LabelStatusInProgress'
    'LabelStatusNeedsHuman'
    'LabelStatusNeedsQc'
    'LabelStatusQueued'
    'LabelAgentCodeGen'
    'LabelAgentDispatcher'
    'LabelAgentDocs'
    'LabelAgentFeasibility'
    'LabelAgentHuman'
    'LabelAgentIdeation'
    'LabelAgentLegal'
    'LabelAgentOrchestrator'
    'LabelAgentPc'
    'LabelAgentQc'
    'LabelAgentResearch'
    'LabelAgentTest'
    'LabelPriorityCritical'
    'LabelPriorityHigh'
    'LabelPriorityLow'
    'LabelPriorityNormal'
    'LabelComplexityAmbiguous'
    'LabelComplexityCloud'
    'LabelComplexityLocal'
    'LabelPhaseDelivery'
    'LabelPhaseExecution'
    'LabelPhaseGate'
    'LabelPhaseIntake'
    'LabelPhaseKilled'
    'LabelPhaseParked'
    'LabelPhaseRequirements'
    'LabelPhaseResearch'
    'LabelPhaseScaffold'
    'LabelHumanCredentials'
    'LabelHumanDecision'
    'LabelHumanReview'
    'LabelHumanWorkstation'
    'StatusLabels'
    'AgentLabels'
    'PriorityLabels'
    'ComplexityLabels'
    'PhaseLabels'
    'HumanLabels'
    'HumanStatusLabels'
    'AllLabels'
)
